name: Metrics
on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches: ["main", "master"]

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # Passo 1 (ANTERIORMENTE achievements): Agora é a imagem de Hábitos com tema merko
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          filename: metrics.plugin.habits.svg
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          theme: merko
          
      # Passo 2 (ANTERIORMENTE habits): Agora é o Calendário de Commits com tema merko
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          filename: metrics.plugin.isocalendar.svg
          plugin_isocalendar: yes
          theme: merko
