name: Metrics
on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches: ["main", "master"]

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # Passo 1: Gera a imagem de Conquistas (Achievements)
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          filename: metrics.plugin.achievements.svg
          plugin_achievements: yes
          plugin_achievements_threshold: C
          plugin_achievements_display: compact
          plugin_achievements_secrets: yes

      # Passo 2: Gera a imagem de Hábitos (Habits)
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          filename: metrics.plugin.habits.svg
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          
      # Passo 3 (NOVO): Gera o Calendário de Commits
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          filename: metrics.plugin.isocalendar.svg
          plugin_isocalendar: yes
